version: 2
jobs:
    test:
        docker:
            - image: circleci/python:3.7.2
              environment:
                TEST_DATABASE_URL: localhost:27017
            - image: circleci/mongo:3.7.9-ram
        steps:
            - checkout
            - run: ./setup_venv.sh
            - run: |
                . env/bin/activate &&
                python -m unittest discover
workflows:
    version: 2
    build_and_test:
        jobs:
            - test