version: 2
jobs:
    test:
        docker:
            - image: circleci/python:3.7.2
              environment:
                TEST_DATABASE_URL: localhost:27017
                TOKEN_SERVICE: http://localhost:12345
                AUTH_SECRET: lkjlksdldkfjlsdjflsdnfkl
                PYTEST_ADDOPTS: tests/
            - image: circleci/mongo:3.7.9-ram
            - image: wipac/token-service:latest
              environment:
                port: 12345
                auth_secret: lkjlksdldkfjlsdjflsdnfkl
              command: [python, test_server.py]
        steps:
            - checkout
            - run: ./setupenv.sh
            - run: |
                . env/bin/activate &&
                pytest --tb=short
workflows:
    version: 2
    build_and_test:
        jobs:
            - test