version: 2
jobs:
    test:
        docker:
            - image: circleci/python:3.8
              environment:
                CI_TEST_ENV: true
                # Both TEST_DATABASE_HOST and TEST_DATABASE_PORT must be defined.
                # Things will break if host is defined and port isn't or vice-versa.
                TEST_DATABASE_HOST: localhost
                TEST_DATABASE_PORT: 27017
                PYTEST_ADDOPTS: tests/
            - image: circleci/mongo:3.7.9-ram
        steps:
            - checkout
            - run: ./setupenv.sh
            - run: |
                source env/bin/activate
                export WIPACTEL_EXPORT_STDOUT=False
                resources/enable_profiling.py
                pytest -vvvvv --tb=short
                resources/profile_queries.py


workflows:
    version: 2
    build_and_test:
        jobs:
            - test
